# This file was generated by GoReleaser. DO NOT EDIT.
cask "sentrie@0" do
  name "sentrie"
  desc "Sentrie policy engine"
  homepage "https://sentrie.sh"
  version "0.0.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sentrie", target: "sentrie@0"

  on_macos do
    on_intel do
      url "https://github.com/sentrie-sh/sentrie/releases/download/v#{version}/sentrie_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/sentrie-sh/sentrie"
      sha256 "3542d3fe4bfbe6175f5f098d7abcbf796b907d692b37ad424ffc63551dbf65e1"
    end
    on_arm do
      url "https://github.com/sentrie-sh/sentrie/releases/download/v#{version}/sentrie_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/sentrie-sh/sentrie"
      sha256 "4dd37b8f4f2fa9e0f037e67d8288b74b5e50a3382df4f31ca91430b93c9705b0"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/sentrie-sh/sentrie/releases/download/v#{version}/sentrie_#{version}_linux_amd64.tar.gz",
        verified: "github.com/sentrie-sh/sentrie"
      sha256 "f920816005dc4074500add627c230715a7b5bb5a4a7ea9636490efffe797fb6d"
    end
    on_arm do
      url "https://github.com/sentrie-sh/sentrie/releases/download/v#{version}/sentrie_#{version}_linux_arm64.tar.gz",
        verified: "github.com/sentrie-sh/sentrie"
      sha256 "172e1977ecb8f0b9bf877708ad32a29f4b3dd230c9318087d29001f7db14a9ad"
    end
  end

  # No zap stanza required
end
