# This file was generated by GoReleaser. DO NOT EDIT.
cask "sentrie@0_0_1_test_release_build006" do
  name "sentrie"
  desc "Sentrie policy engine"
  homepage "https://sentrie.sh"
  version "0.0.1-test.release.build006"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sentrie", target: "sentrie@0.0.1-test.release.build006"

  on_macos do
    on_intel do
      url "https://github.com/sentrie-sh/sentrie/releases/download/v#{version}/sentrie_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/sentrie-sh/sentrie"
      sha256 "b19c3d87646182fc8590c1d2c97ed2423ccbbf4d4e69b1f7dc4e37e81f9e7883"
    end
    on_arm do
      url "https://github.com/sentrie-sh/sentrie/releases/download/v#{version}/sentrie_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/sentrie-sh/sentrie"
      sha256 "ec6404884edd652064c388c6398f3cd1737769dee54a14a4e5bb5a8bc94ea00c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/sentrie-sh/sentrie/releases/download/v#{version}/sentrie_#{version}_linux_amd64.tar.gz",
        verified: "github.com/sentrie-sh/sentrie"
      sha256 "b4451701cebc2567c92e567ef9f6a31c1155a5e67c2b43343a60acc93a7cca93"
    end
    on_arm do
      url "https://github.com/sentrie-sh/sentrie/releases/download/v#{version}/sentrie_#{version}_linux_arm64.tar.gz",
        verified: "github.com/sentrie-sh/sentrie"
      sha256 "b8fb9665e12c9d9e5dd43b2916f048f1719b948a46914bdf9111736aaebe3882"
    end
  end

  # No zap stanza required
end
