# This file was generated by GoReleaser. DO NOT EDIT.
cask "sentrie" do
  name "sentrie"
  desc "Sentrie policy engine"
  homepage "https://sentrie.sh"
  version "0.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sentrie"

  on_macos do
    on_intel do
      url "https://github.com/sentrie-sh/sentrie/releases/download/v#{version}/sentrie_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/sentrie-sh/sentrie"
      sha256 "d8c63ac24537426701727abff43841f0576e92ae43fe0c3ab074ccfdb4d76973"
    end
    on_arm do
      url "https://github.com/sentrie-sh/sentrie/releases/download/v#{version}/sentrie_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/sentrie-sh/sentrie"
      sha256 "a50c9eccb2f6e77d55b101b8374de8cef2fdaa7062d86fbb5dc6f4f613f5718c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/sentrie-sh/sentrie/releases/download/v#{version}/sentrie_#{version}_linux_amd64.tar.gz",
        verified: "github.com/sentrie-sh/sentrie"
      sha256 "73deaf659591e73bb058c3cc907b38889f90b893e3563bf9a692a09b48a204c3"
    end
    on_arm do
      url "https://github.com/sentrie-sh/sentrie/releases/download/v#{version}/sentrie_#{version}_linux_arm64.tar.gz",
        verified: "github.com/sentrie-sh/sentrie"
      sha256 "0aa04082a80e8f1d7fe92d44ac8d231ce4b9c9dc171cb25531a92eca5841cc57"
    end
  end

  # No zap stanza required
end
